name: Python App -> Deployment

on:
  push:
    branches: [ production ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up Python 3.10.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8 # this will check the python code for syntax errors/editing errors
      run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
    - name: Add remote origin
      if: github.ref == 'refs/heads/production' && job.status == 'success' # We specify that this action will ONLY run if everything up to now is successful- so if theres a fail in the tests, then this will not be deployed.
      run: | # Make sure to add ENVIRONMENT VARIABLES in REPOSITORY SETTINGS 1. HEROKU_API_KEY 2. HEROKU_APP_NAME
      
      # git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      # git remote add [service] [api] [appkey].git
      
    - name: Deploy to Deployment [Name Of Service]
      run: |
        # git push heroku HEAD:main -f
        checkstring: "ok"
        rollbackonhealthcheckfailed: true
